

services:
 

  server:
    build: ./service
    ports:
      - "5001:5001"
    volumes:
      - ./service:/app
      - /app/node_modules
    env_file:
      - ./service/.env
    depends_on:
      - db

  db: 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: hnation-db
    ports:
      - "5434:5433" 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
