services:
 

  server:
    build: ./service
    ports:
      - "5000:5000"
    volumes:
      - ./service:/app
      - /app/node_modules
    env_file:
      - ./service/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./db.env
    ports:
      - "5434:5432"  # Corrected container port for Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
